#!/usr/bin/env bash
# Builds the macOS app that wraps the extension for Safari.
#
#   npm run safari-app-build                  build the committed Xcode project (Release)
#   npm run safari-app-build -- Debug         build for debugging inside Xcode only; Safari
#                                             will not load a Debug build, because Xcode embeds
#                                             a debug dylib the extension cannot resolve
#   npm run safari-app-build -- --regenerate  recreate the Xcode project, then build
#   npm run safari-app-build -- --install     build, then install over the copy Safari loads
#
# The Xcode project under safari/ is generated by safari-web-extension-converter and committed.
# Regenerate it whenever files are added to or removed from addon/, because the converter writes an
# explicit reference for every resource file and the build fails on a reference it cannot resolve.
# Regeneration is scripted rather than manual because the converter has to be pointed at the built
# payload (not at addon/ directly) and because its bundle identifiers need patching afterwards.

set -euo pipefail

cd "$(dirname "$0")/.."

CONFIGURATION="Release"   # Debug embeds a debug dylib that Safari will not load
REGENERATE=0
INSTALL=0
for arg in "$@"; do
  case "$arg" in
    --regenerate) REGENERATE=1 ;;
    --install) INSTALL=1 ;;
    Debug|Release) CONFIGURATION="$arg" ;;
    *) echo "error: unknown argument '$arg'" >&2; exit 2 ;;
  esac
done

# Safari cannot load a Debug build at all, so installing one would replace a working extension with
# one that silently fails to appear.
if [ "$INSTALL" = "1" ] && [ "$CONFIGURATION" = "Debug" ]; then
  echo "error: --install refuses a Debug build; Safari will not load it." >&2
  exit 2
fi

APP_NAME="SF Inspector"
BUNDLE_ID="be.hoofdvogel.sfinspector"
PROJECT="safari/$APP_NAME/$APP_NAME.xcodeproj"
RESOURCES="safari/$APP_NAME/$APP_NAME Extension/Resources"
PAYLOAD="target/safari/dist"

# Safari lists one entry in Settings > Extensions per bundle path it has seen, and nothing prunes
# that list. Installing to one fixed path therefore keeps it to a single entry that updates in
# place, instead of a new near-identical duplicate for every build.
INSTALL_DIR="$HOME/Applications"
INSTALLED="$INSTALL_DIR/$APP_NAME.app"

# xcode-select often points at the Command Line Tools, which have no xcodebuild. Prefer a full
# Xcode when one is installed rather than requiring "sudo xcode-select -s".
if ! xcrun --find xcodebuild >/dev/null 2>&1; then
  if [ -d /Applications/Xcode.app ]; then
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
  else
    echo "error: Xcode is required to build the Safari app, but it was not found." >&2
    exit 1
  fi
fi

# Derived data must live outside the repository: this checkout can sit in an iCloud-synced folder,
# and the sync layer stamps com.apple.FinderInfo onto build output, which makes codesign fail with
# "resource fork, Finder information, or similar detritus not allowed".
DERIVED_DATA="${TMPDIR:-/tmp}/sf-inspector-safari"

echo "==> Building extension payload"
node scripts/release-build.js safari

# The project no longer lists the payload file by file: its "Copy extension resources" phase copies
# the whole Resources directory, so adding or removing a file in addon/ needs no change to it. That
# is what makes the project something that can be owned and committed rather than regenerated --
# regeneration throws away every setting on it, and signing, entitlements and versions all live
# there now.
#
# --regenerate is still available for the rare case where the project itself has to be rebuilt from
# the converter, but it is deliberately not automatic any more.

if [ "$REGENERATE" = "1" ] || [ ! -d "$PROJECT" ]; then
  if [ -d "$PROJECT" ]; then
    echo "==> Regenerating the Xcode project"
    echo "    This discards everything set on it: signing, entitlements, versions, build phases."
    echo "    Check git diff before committing the result."
  else
    echo "==> No Xcode project found; generating one"
  fi
  rm -rf safari
  xcrun safari-web-extension-converter "$PAYLOAD" \
    --project-location safari \
    --app-name "$APP_NAME" \
    --bundle-identifier "$BUNDLE_ID" \
    --macos-only --swift --copy-resources --no-open --no-prompt --force

  # The converter derives the app's identifier from the app name but the extension's from
  # --bundle-identifier, so the two disagree and Xcode rejects the embedded extension with
  # "Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier."
  APP_ID_FROM_NAME="be.hoofdvogel.${APP_NAME// /-}"
  perl -pi -e "s/PRODUCT_BUNDLE_IDENTIFIER = \"\Q$APP_ID_FROM_NAME\E\";/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" \
    "$PROJECT/project.pbxproj"

  # Xcode's copy phase never deletes, so a resource dropped from the payload lingers in the built
  # bundle and would ship. Regeneration is exactly when the file list changed, so discard the
  # previous build products with it.
  rm -rf "$DERIVED_DATA"
fi

echo "==> Syncing payload into the Xcode project"
mkdir -p "$RESOURCES"
rsync -a --delete "$PAYLOAD/" "$RESOURCES/"

# Sign with a real Apple Development identity when the keychain has one, so Safari loads the
# extension normally. Without one, fall back to ad-hoc signing, which still builds but forces
# Safari's "Allow unsigned extensions" (a setting that resets on every restart).
#
# If the keychain holds the certificate but no valid identity, the usual cause is a missing Apple
# WWDR intermediate: certificates issued by WWDR G3 do not validate against the older G1, which
# expired in 2023. security find-identity then reports CSSMERR_TP_NOT_TRUSTED, and the fix is to
# install https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer.
TEAM="$(security find-certificate -c "Apple Development" -p 2>/dev/null \
  | openssl x509 -noout -subject 2>/dev/null \
  | sed -n 's/.*OU=\([A-Z0-9]\{10\}\).*/\1/p')"

if [ -n "$TEAM" ] && security find-identity -v -p codesigning 2>/dev/null | grep -q "Apple Development"; then
  echo "==> Signing as team $TEAM"
  SIGNING_ARGS=(CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM="$TEAM")
else
  echo "==> No Apple Development identity found; signing ad-hoc"
  echo "    Safari will only load this with Develop > Allow Unsigned Extensions enabled."
  SIGNING_ARGS=(CODE_SIGN_IDENTITY="-" CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM="")
fi

# The extension's product is discarded so the target is always rebuilt, and therefore always
# re-signed.
#
# Its resources are copied by a build phase rather than listed in the project, which is what lets
# addon/ change without touching the project -- but it also means Xcode cannot see when the payload
# changed. On an incremental build it concluded the target was up to date, skipped it, and left the
# previous signature in place while the phase rewrote the files underneath it. codesign then
# reported "a sealed resource is missing or invalid" for every file that had changed. Rebuilding
# just the appex costs a few seconds; the app target and its Swift compilation stay cached.
APPEX="$DERIVED_DATA/Build/Products/$CONFIGURATION/$APP_NAME Extension.appex"
rm -rf "$APPEX"

echo "==> Building $CONFIGURATION"
LOG="$(mktemp -t safari-build)"
set +e
xcodebuild -project "$PROJECT" \
  -scheme "$APP_NAME" \
  -configuration "$CONFIGURATION" \
  -derivedDataPath "$DERIVED_DATA" \
  "${SIGNING_ARGS[@]}" >"$LOG" 2>&1
STATUS=$?
set -e

if [ "$STATUS" -ne 0 ]; then
  echo
  echo "Build failed:" >&2
  grep -E "error:|warning: The following keys" "$LOG" >&2 || tail -30 "$LOG" >&2
  echo
  echo "Full log: $LOG" >&2
  exit "$STATUS"
fi

grep -E "warning: The following keys" -A6 "$LOG" || true
rm -f "$LOG"

APP="$DERIVED_DATA/Build/Products/$CONFIGURATION/$APP_NAME.app"

# Xcode registers its build products with LaunchServices, so every build leaves another copy of the
# app known to the system. Safari builds its extension list from that, which is why repeated builds
# produce duplicate entries in Settings > Extensions. The build product is a temporary artifact and
# has no business being registered; only the copy the user installs should be.
LSREGISTER=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister
if [ -x "$LSREGISTER" ]; then
  "$LSREGISTER" -u "$APP" 2>/dev/null || true
fi

echo
echo "Built: $APP"

if [ "$INSTALL" = "0" ]; then
  echo
  echo "Built but not installed: Safari still loads whatever is at"
  echo "  $INSTALLED"
  echo "Re-run with --install to replace it, or open the build above to register it separately."
  echo
  echo "To load this build in Safari:"
  echo "  1. open \"$APP\""
  if [ -z "${TEAM:-}" ]; then
    echo "  2. Safari > Settings > Advanced > enable \"Show features for web developers\""
    echo "  3. Safari > Developer > check \"Allow unsigned extensions\" (resets on each Safari restart)"
    echo "  4. Safari > Settings > Extensions > enable $APP_NAME"
  else
    echo "  2. Safari > Settings > Extensions > enable $APP_NAME"
  fi
  echo
  echo "Then grant it access to your Salesforce domains, or it will behave as if signed out."
  exit 0
fi

echo "==> Installing to $INSTALLED"
mkdir -p "$INSTALL_DIR"

# Replaced wholesale rather than synced into place. Xcode's copy phases never delete, and a stale
# file left inside a signed bundle breaks the seal: codesign --verify then fails and Safari refuses
# the extension. Staging beside the destination first keeps a failed copy from destroying the
# working install.
STAGE="$INSTALL_DIR/.$APP_NAME.app.incoming"
rm -rf "$STAGE"
cp -R "$APP" "$STAGE"
rm -rf "$INSTALLED"
mv "$STAGE" "$INSTALLED"

# The bundle is only worth installing if its signature survived the copy; an unverifiable bundle is
# one Safari will decline to load, and it is better to say so here than to leave that to be
# discovered in Settings > Extensions.
if ! codesign --verify --strict "$INSTALLED" 2>/dev/null; then
  echo "warning: the installed bundle does not pass codesign --verify." >&2
  echo "         Safari may refuse to load it." >&2
fi

if [ -x "$LSREGISTER" ]; then
  "$LSREGISTER" -f "$INSTALLED"
fi

# Registering the bundle is not enough on its own: Safari only offers a web extension once the app
# containing it has actually been launched, which is what hands the appex to pluginkit. Skip this
# and the extension is installed, signed and registered, and still absent from Settings >
# Extensions. Launched in the background so a build does not steal focus or leave a window in the
# way; that is enough for the registration to happen.
echo "==> Registering the extension (launching the app once)"
open -g -j "$INSTALLED"

# Wait for pluginkit to see it rather than assuming, so a failure here is reported now instead of
# turning into a hunt through Safari's settings.
for _ in 1 2 3 4 5 6 7 8 9 10; do
  if pluginkit -mv -p com.apple.Safari.web-extension 2>/dev/null | grep -q "$BUNDLE_ID"; then
    REGISTERED=1
    break
  fi
  sleep 0.5
done

echo
echo "Installed: $INSTALLED"
if [ -z "${REGISTERED:-}" ]; then
  echo
  echo "warning: the extension is installed but has not appeared in the system's plug-in list." >&2
  echo "         Open it by hand and check Safari > Settings > Extensions:" >&2
  echo "           open \"$INSTALLED\"" >&2
fi
echo
if pgrep -xq Safari; then
  echo "Safari is running and still has the previous build loaded."
  echo "Quit and reopen Safari to pick this one up."
else
  echo "Reopen Safari to pick it up."
fi
echo
echo "The bundle identifier and path are unchanged, so $APP_NAME stays enabled with the site"
echo "permissions it already had; it should not reappear as a new extension to approve."
