#!/usr/bin/env bash
# Builds the macOS app that wraps the extension for Safari.
#
#   npm run safari-app-build                  build the committed Xcode project (Debug)
#   npm run safari-app-build -- Release       build for release
#   npm run safari-app-build -- --regenerate  recreate the Xcode project, then build
#
# The Xcode project under safari/ is generated by safari-web-extension-converter and committed.
# Regenerate it whenever files are added to or removed from addon/, because the converter writes an
# explicit reference for every resource file and the build fails on a reference it cannot resolve.
# Regeneration is scripted rather than manual because the converter has to be pointed at the built
# payload (not at addon/ directly) and because its bundle identifiers need patching afterwards.

set -euo pipefail

cd "$(dirname "$0")/.."

CONFIGURATION="Debug"
REGENERATE=0
for arg in "$@"; do
  case "$arg" in
    --regenerate) REGENERATE=1 ;;
    Debug|Release) CONFIGURATION="$arg" ;;
    *) echo "error: unknown argument '$arg'" >&2; exit 2 ;;
  esac
done

APP_NAME="Inspector Reloaded"
BUNDLE_ID="be.hoofdvogel.inspectorreloaded"
PROJECT="safari/$APP_NAME/$APP_NAME.xcodeproj"
RESOURCES="safari/$APP_NAME/$APP_NAME Extension/Resources"
PAYLOAD="target/safari/dist"

# xcode-select often points at the Command Line Tools, which have no xcodebuild. Prefer a full
# Xcode when one is installed rather than requiring "sudo xcode-select -s".
if ! xcrun --find xcodebuild >/dev/null 2>&1; then
  if [ -d /Applications/Xcode.app ]; then
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
  else
    echo "error: Xcode is required to build the Safari app, but it was not found." >&2
    exit 1
  fi
fi

# Derived data must live outside the repository: this checkout can sit in an iCloud-synced folder,
# and the sync layer stamps com.apple.FinderInfo onto build output, which makes codesign fail with
# "resource fork, Finder information, or similar detritus not allowed".
DERIVED_DATA="${TMPDIR:-/tmp}/inspector-reloaded-safari"

echo "==> Building extension payload"
node scripts/release-build.js safari

if [ "$REGENERATE" = "1" ] || [ ! -d "$PROJECT" ]; then
  echo "==> Regenerating the Xcode project"
  rm -rf safari
  xcrun safari-web-extension-converter "$PAYLOAD" \
    --project-location safari \
    --app-name "$APP_NAME" \
    --bundle-identifier "$BUNDLE_ID" \
    --macos-only --swift --copy-resources --no-open --no-prompt --force

  # The converter derives the app's identifier from the app name but the extension's from
  # --bundle-identifier, so the two disagree and Xcode rejects the embedded extension with
  # "Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier."
  APP_ID_FROM_NAME="be.hoofdvogel.${APP_NAME// /-}"
  perl -pi -e "s/PRODUCT_BUNDLE_IDENTIFIER = \"\Q$APP_ID_FROM_NAME\E\";/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" \
    "$PROJECT/project.pbxproj"
fi

echo "==> Syncing payload into the Xcode project"
mkdir -p "$RESOURCES"
rsync -a --delete "$PAYLOAD/" "$RESOURCES/"

echo "==> Building $CONFIGURATION"
LOG="$(mktemp -t safari-build)"
set +e
xcodebuild -project "$PROJECT" \
  -scheme "$APP_NAME" \
  -configuration "$CONFIGURATION" \
  -derivedDataPath "$DERIVED_DATA" \
  CODE_SIGN_IDENTITY="-" \
  CODE_SIGN_STYLE=Manual \
  DEVELOPMENT_TEAM="" >"$LOG" 2>&1
STATUS=$?
set -e

if [ "$STATUS" -ne 0 ]; then
  echo
  echo "Build failed:" >&2
  grep -E "error:|warning: The following keys" "$LOG" >&2 || tail -30 "$LOG" >&2
  echo
  echo "Full log: $LOG" >&2
  exit "$STATUS"
fi

grep -E "warning: The following keys" -A6 "$LOG" || true
rm -f "$LOG"

APP="$DERIVED_DATA/Build/Products/$CONFIGURATION/$APP_NAME.app"
echo
echo "Built: $APP"
echo
echo "To load it in Safari:"
echo "  1. open \"$APP\""
echo "  2. Safari > Settings > Advanced > enable \"Show features for web developers\""
echo "  3. Safari > Developer > check \"Allow unsigned extensions\" (resets on each Safari restart)"
echo "  4. Safari > Settings > Extensions > enable $APP_NAME"
