#!/usr/bin/env bash
# Builds the macOS app that wraps the extension for Safari.
#
#   npm run safari-app-build                  build the committed Xcode project (Release)
#   npm run safari-app-build -- Debug         build for debugging inside Xcode only; Safari
#                                             will not load a Debug build, because Xcode embeds
#                                             a debug dylib the extension cannot resolve
#   npm run safari-app-build -- --regenerate  recreate the Xcode project, then build
#
# The Xcode project under safari/ is generated by safari-web-extension-converter and committed.
# Regenerate it whenever files are added to or removed from addon/, because the converter writes an
# explicit reference for every resource file and the build fails on a reference it cannot resolve.
# Regeneration is scripted rather than manual because the converter has to be pointed at the built
# payload (not at addon/ directly) and because its bundle identifiers need patching afterwards.

set -euo pipefail

cd "$(dirname "$0")/.."

CONFIGURATION="Release"   # Debug embeds a debug dylib that Safari will not load
REGENERATE=0
for arg in "$@"; do
  case "$arg" in
    --regenerate) REGENERATE=1 ;;
    Debug|Release) CONFIGURATION="$arg" ;;
    *) echo "error: unknown argument '$arg'" >&2; exit 2 ;;
  esac
done

APP_NAME="SF Inspector"
BUNDLE_ID="be.hoofdvogel.sfinspector"
PROJECT="safari/$APP_NAME/$APP_NAME.xcodeproj"
RESOURCES="safari/$APP_NAME/$APP_NAME Extension/Resources"
PAYLOAD="target/safari/dist"

# xcode-select often points at the Command Line Tools, which have no xcodebuild. Prefer a full
# Xcode when one is installed rather than requiring "sudo xcode-select -s".
if ! xcrun --find xcodebuild >/dev/null 2>&1; then
  if [ -d /Applications/Xcode.app ]; then
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
  else
    echo "error: Xcode is required to build the Safari app, but it was not found." >&2
    exit 1
  fi
fi

# Derived data must live outside the repository: this checkout can sit in an iCloud-synced folder,
# and the sync layer stamps com.apple.FinderInfo onto build output, which makes codesign fail with
# "resource fork, Finder information, or similar detritus not allowed".
DERIVED_DATA="${TMPDIR:-/tmp}/sf-inspector-safari"

echo "==> Building extension payload"
node scripts/release-build.js safari

# The generated project references every resource by name, so its file list has to match the payload
# exactly. An added file is copied into Resources/ but never into the built bundle, and that fails
# silently: the manifest ends up naming a script the extension does not ship. A removed file leaves
# a dangling reference and fails the build outright.
#
# Compare against the list recorded when the project was generated. Resources/ itself is no use for
# this, because the rsync below rewrites it on every run and so always appears to match.
PAYLOAD_LIST="safari/.payload-files"

if [ "$REGENERATE" = "0" ] && [ -d "$PROJECT" ]; then
  if ! diff -q "$PAYLOAD_LIST" <(cd "$PAYLOAD" && ls -A) >/dev/null 2>&1; then
    echo "==> Payload no longer matches what the Xcode project was generated from; regenerating"
    REGENERATE=1
  fi
fi

if [ "$REGENERATE" = "1" ] || [ ! -d "$PROJECT" ]; then
  echo "==> Regenerating the Xcode project"
  rm -rf safari
  xcrun safari-web-extension-converter "$PAYLOAD" \
    --project-location safari \
    --app-name "$APP_NAME" \
    --bundle-identifier "$BUNDLE_ID" \
    --macos-only --swift --copy-resources --no-open --no-prompt --force

  # The converter derives the app's identifier from the app name but the extension's from
  # --bundle-identifier, so the two disagree and Xcode rejects the embedded extension with
  # "Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier."
  APP_ID_FROM_NAME="be.hoofdvogel.${APP_NAME// /-}"
  perl -pi -e "s/PRODUCT_BUNDLE_IDENTIFIER = \"\Q$APP_ID_FROM_NAME\E\";/PRODUCT_BUNDLE_IDENTIFIER = $BUNDLE_ID;/g" \
    "$PROJECT/project.pbxproj"

  (cd "$PAYLOAD" && ls -A) > "$PAYLOAD_LIST"

  # Xcode's copy phase never deletes, so a resource dropped from the payload lingers in the built
  # bundle and would ship. Regeneration is exactly when the file list changed, so discard the
  # previous build products with it.
  rm -rf "$DERIVED_DATA"
fi

echo "==> Syncing payload into the Xcode project"
mkdir -p "$RESOURCES"
rsync -a --delete "$PAYLOAD/" "$RESOURCES/"

# Sign with a real Apple Development identity when the keychain has one, so Safari loads the
# extension normally. Without one, fall back to ad-hoc signing, which still builds but forces
# Safari's "Allow unsigned extensions" (a setting that resets on every restart).
#
# If the keychain holds the certificate but no valid identity, the usual cause is a missing Apple
# WWDR intermediate: certificates issued by WWDR G3 do not validate against the older G1, which
# expired in 2023. security find-identity then reports CSSMERR_TP_NOT_TRUSTED, and the fix is to
# install https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer.
TEAM="$(security find-certificate -c "Apple Development" -p 2>/dev/null \
  | openssl x509 -noout -subject 2>/dev/null \
  | sed -n 's/.*OU=\([A-Z0-9]\{10\}\).*/\1/p')"

if [ -n "$TEAM" ] && security find-identity -v -p codesigning 2>/dev/null | grep -q "Apple Development"; then
  echo "==> Signing as team $TEAM"
  SIGNING_ARGS=(CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM="$TEAM")
else
  echo "==> No Apple Development identity found; signing ad-hoc"
  echo "    Safari will only load this with Develop > Allow Unsigned Extensions enabled."
  SIGNING_ARGS=(CODE_SIGN_IDENTITY="-" CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM="")
fi

echo "==> Building $CONFIGURATION"
LOG="$(mktemp -t safari-build)"
set +e
xcodebuild -project "$PROJECT" \
  -scheme "$APP_NAME" \
  -configuration "$CONFIGURATION" \
  -derivedDataPath "$DERIVED_DATA" \
  "${SIGNING_ARGS[@]}" >"$LOG" 2>&1
STATUS=$?
set -e

if [ "$STATUS" -ne 0 ]; then
  echo
  echo "Build failed:" >&2
  grep -E "error:|warning: The following keys" "$LOG" >&2 || tail -30 "$LOG" >&2
  echo
  echo "Full log: $LOG" >&2
  exit "$STATUS"
fi

grep -E "warning: The following keys" -A6 "$LOG" || true
rm -f "$LOG"

APP="$DERIVED_DATA/Build/Products/$CONFIGURATION/$APP_NAME.app"
echo
echo "Built: $APP"
echo
echo "To load it in Safari:"
echo "  1. open \"$APP\""
if [ -z "${TEAM:-}" ]; then
  echo "  2. Safari > Settings > Advanced > enable \"Show features for web developers\""
  echo "  3. Safari > Developer > check \"Allow unsigned extensions\" (resets on each Safari restart)"
  echo "  4. Safari > Settings > Extensions > enable $APP_NAME"
else
  echo "  2. Safari > Settings > Extensions > enable $APP_NAME"
fi
echo
echo "Then grant it access to your Salesforce domains, or it will behave as if signed out."
echo "Safari lists an entry per extension build it has seen; quit Safari to clear stale ones."
